### ISSUE TITLE
November 2019 - Content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Enterprise-class-networking#41]
This workshop is scheduled for a content update.  Opsgility, please review the workshop and provide your update suggestions for SME review here.

**Comment by paulopsgility** [comment]
Here are our proposed changes. We have a bunch of updates and additions and we are also suggesting some cuts to save time.

Lab:
1. Update and enhance exercise descriptions to explain what you're doing and why.

1. Update solution architecture diagram and description.

1. Update Exercise 8 to use a more "Enterprise-class" approach to VPN with fully redundant active-active gateways etc. https://blogs.technet.microsoft.com/rspitz/2018/02/19/just-enough-bgp-to-get-your-azure-dual-redundancy-active-active-vpn-gateways-up-and-running/ 

1. Update exercise 9 to show the benefit of using ASGs, all the VMs in a single subnet. And verify the ASG is working (show not-allowed connections are blocked)

1. Review Azure Firewall content. Check all IP ranges / subnet names are consistent. Check inbound/outbound rules are consistent between FW and route tables. Verify permitted / blocked traffic flows (using Network Watcher?) Demonstrate the value the FW is bringing (e.g. outbound traffic FQDN-based rule)

1. Pre-deploy CloudShop in the ‘before the lab’ guide. Then reorganize the rest of the lab as 4 exercises. Each exercise includes verification.
    - Tiering via NSGs/ASGs
    - Peering + Bastion
    - Adding routes + FW
    - HA S2S VPN

1. Cut Exercise 10 (storage firewall / service endpoints), since the storage account is never actually used for anything. In addition, with Private Link coming, we will be refactoring this topic in future anyway.

1. Cut DDOS. Right now we turn it on but never test it or demonstrate its value.

WDS:

1. Align with lab, HA requirements for VPN, use ASGs to avoid mgmt overhead and ip address waste of lots of subnets and increase flexibility.

**Comment by rdendtler** [comment]
1. Current solution architecture is Vnet representing "On-premises", Vnet representing "hub" and a peered Vnet representing a workload VNET.  Could we address the following:

- Most/many enterprise deployments will have the firewall in the "hub" vnet, and pass traffic to on-premises (and to internet) via that, as opposed a FW in each externally accessible app... 
- If we can centralize Azure FW in WGVnetRG1, then would recommend having 2 vnets to peer to it, and show traffic routing to a vm in either

2. Agree on the use of ASG and a flatter network for mutli-tier app.
3. Would like to see us incorporate monitoring/network watcher.  This is an area I see a number of customers fail to do (both on the VNET to VNET/ER and on the Peer/IP Flow). Connection monitor and Network watcher would be important.  I would recommend this as a separate section of the overall content.  
4.  Bastion doesn't work across peering -yet-...once it does it would well placed in the hub.. 
5. I know JIT is incorporated in the Security demo...but should we also review here?  It may be too complicated of a discussion

**Comment by DawnmarieDesJardins** [comment]
Please see issue #42

**Comment by DawnmarieDesJardins** [comment]
Closing issue with Nov 2019 update merge
