### ISSUE TITLE
Missing installation of WGMGMT1

### ISSUE THREAD

**Issue by fatihdurgut** [microsoft/MCW-Enterprise-class-networking#58]
WGMGMT1 installation is missing in the HOL document and you are asking us to connect it in exercise 9. See below. 

On the jump host virtual machine (**WGMGMT1**), open Internet Explorer and browse to the web application deployed to the WGVnet2 via the private IP address of the Azure Load Balancer(10.8.0.100). Note that this traffic is routed (and allowed) via Azure Firewall.On the jump host virtual machine (WGMGMT1), open Internet Explorer and browse to the web application deployed to the WGVnet2 via the private IP address of the Azure Load Balancer(10.8.0.100). Note that this traffic is routed (and allowed) via Azure Firewall.

**Comment by dwnatwick** [comment]
@fatihdurgut..  Can you clarify that this issue is still valid?  You opened a separate issue #59 that mentioned that you are connecting via this MGMGMT1 jump host.  Were you able to find the installation of WGMGMT1 or did you manually complete this?   These bullets at the end of Exercise 9 should actually reference Bastion connections to WGWEB1 and WGWEB2, so they will be updated.  The jump host is no longer valid for this workshop.  Leave this issue open awaiting your response.  Thank you.

**Comment by fatihdurgut** [comment]
Hello @dwnatwick , 
This is still valid, I installed the WGMGMT1 by myself manual. I couldn't find any documentation how to install it.  
thanks.

**Comment by dwnatwick** [comment]
Thank you, @fatihdurgut.  The WGMGMT1 jump host is no longer valid for this MCW.  I am going to close this issue with this comment.  I will leave issue #59 open since there needs to be an update to those connection testing steps where you utilize the Bastion Host instead of a jump host.  Thank you very much.
